version: '3.3'

services:
    mongo1:
        hostname: mongo1
        container_name: gogqlserver_mongo1
        image: mongo:4.2.2-bionic
        deploy:
          resources:
            limits:
              cpus: '4.00'
              memory: 16G
            reservations:
              cpus: '1.00'
              memory: 8G      
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=dtp-user
            - MONGO_INITDB_ROOT_PASSWORD=test
            - MONGO_INITDB_DATABASE=myFiles
        expose:
            - 27017
        ports:
            - 27017:27017
        volumes:
            - /home/payall/init-mongo.js:/docker-entry-point-initdb.d/init-mongo.js:ro
            - /home/payall/data0:/data/db
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
        
    mongo2:
        hostname: mongo2
        container_name: gogqlserver_mongo2
        image: mongo:4.2.2-bionic
        deploy:
          resources:
            limits:
              cpus: '4.00'
              memory: 16G
            reservations:
              cpus: '1.00'
              memory: 8G 
        restart: unless-stopped
        expose:
            - 27017
        ports:
            - 27018:27017
        volumes:
            - /home/payall/init-mongo.js:ro
            - /home/payall/data1:/data/db
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

    mongo3:
        hostname: mongo3
        container_name: gogqlserver_mongo3
        image: mongo:4.2.2-bionic
        deploy:
          resources:
            limits:
              cpus: '4.00'
              memory: 16G
            reservations:
              cpus: '1.00'
              memory: 8G 
        restart: unless-stopped
        expose:
            - 27017
        ports:
            - 27019:27017
        volumes:
            - /home/payall/init-mongo.js:/docker-entry-point-initdb.d/init-mongo.js:ro
            - /home/payall/data2:/data/db
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
